#!/usr/bin/env ruby

# Create SimpleCov test coverage report.
#
# coverage_folder - the directory in which to store coverage report
#                   this defaults to `log/coverage`.
#
config :qed, :profile=>:cov do
  require 'simplecov'

  dir = properties.coverage_folder

  SimpleCov.start do
    coverage_dir(dir || 'log/coverage')
    #add_group "Label", "lib/qed/directory"
  end
end

#
config :example do
  puts "Configuration Example!"
end

