#!mast -x man/*/index.txt .ruby .yardopts bin lib man spec test [A-Z]*.*
.ruby
.yardopts
lib/confection/basic_object.rb
lib/confection/config.rb
lib/confection/controller.rb
lib/confection/dsl.rb
lib/confection/manage.rb
lib/confection.rb
HISTORY.rdoc
README.rdoc
COPYING.rdoc
